<i>Copyright (c) Recommenders contributors.</i>

<i>Licensed under the MIT License.</i>

# LightGCN - simplified GCN model for recommendation

This notebook serves as an introduction to LightGCN [1], which is an simple, linear and neat Graph Convolution Network (GCN) [3] model for recommendation.

## 0 Global Settings and Imports

In [1]:
import logging
import sys

import pandas as pd
import torch

from recommenders.datasets import movielens
from recommenders.datasets.python_splitters import python_stratified_split
from recommenders.evaluation.python_evaluation import (
    map_at_k,
    ndcg_at_k,
    precision_at_k,
    recall_at_k,
)
from recommenders.models.deeprec.DataModel.ImplicitCF import ImplicitCF
from recommenders.models.deeprec.models.graphrec.lightgcn import LightGCN
from recommenders.utils.constants import SEED as DEFAULT_SEED
from recommenders.utils.notebook_utils import store_metadata
from recommenders.utils.timer import Timer

logging.basicConfig(level=logging.INFO, format="%(message)s")

print(f"System version: {sys.version}")
print(f"Pandas version: {pd.__version__}")
print(f"PyTorch version: {torch.__version__}")

System version: 3.11.0 (main, Mar 16 2025, 13:39:19) [GCC 11.4.0]
Pandas version: 2.3.3
PyTorch version: 2.5.1+cu121

In [2]:
# top k items to recommend
TOP_K = 10

# Select MovieLens data size: 100k, 1m, 10m, or 20m
MOVIELENS_DATA_SIZE = "100k"

# Model parameters
EPOCHS = 50
BATCH_SIZE = 1024

SEED = DEFAULT_SEED  # Set None for non-deterministic results

user_file = "../../tests/resources/deeprec/lightgcn/user_embeddings.csv"
item_file = "../../tests/resources/deeprec/lightgcn/item_embeddings.csv"

## 1 LightGCN model

LightGCN is a simplified version of Neural Graph Collaborative Filtering (NGCF) [4], which adapts GCNs in recommendation systems.

### 1.1 Graph Networks in Recommendation Systems

GCN are networks that can learn patterns in graph data. They can be applied in many fields, but they are particularly well suited for Recommendation Systems, because of their ability to encode relationships.

In traditional models like matrix factorization [5], user and items are represented as embeddings. And the interaction, which is the signal that encodes the behavior, is not part of the embeddings, but it is represented in the loss function, typically as a dot product. 

Despite their effectiveness, some authors [1,4] argue that these methods are not sufficient to yield satisfactory embeddings for collaborative filtering. The key reason is that the embedding function lacks an explicit encoding of the crucial collaborative signal, which is latent in user-item interactions to reveal the behavioral similarity between users (or items). 

**GCNs can be used to encode the interaction signal in the embeddings**. Interacted items can be seen as user´s features, because they provide direct evidence on a user’s preference. Similarly, the users that consume an item can be treated as the item’s features and used to measure the collaborative similarity of two items. A natural way to incorporate the interaction signal in the embedding is by exploiting the high-order connectivity from user-item interactions.

In the figure below, the user-item interaction is shown (to the left) as well as the concept of higher-order connectivity (to the right).

<img src="https://raw.githubusercontent.com/recommenders-team/resources/main/images/High_order_connectivity.png" width=500 style="display:block; margin-left:auto; margin-right:auto;">

The high-order connectivity shows the collaborative signal in a graph form. For example, the path $u_1 ← i_2 ← u2$ indicates the behavior
similarity between $u_1$ and $u_2$, as both users have interacted with $i_2$; the longer path $u_1 ← i_2 ← u_2 ← i_4$ suggests that $u_1$ is likely to adopt $i_4$, since her similar user $u_2$ has consumed $i_4$ before. Moreover, from the holistic view of $l = 3$, item $i_4$ is more likely to be of interest to $u_1$ than item $i_5$, since there are two paths connecting $(i_4,u_1)$, while only one path connects $(i_5,u_1)$.

Based on this high-order connectivity, NGCF [4] defines an embedding propagation layer, which refines a user’s (or an item’s) embedding by aggregating the embeddings of the interacted items (or users). By stacking multiple embedding propagation layers, we can enforce the embeddings
to capture the collaborative signal in high-order connectivities.

More formally, let $\mathbf{e}_{u}^{0}$ denote the original embedding of user $u$ and $\mathbf{e}_{i}^{0}$ denote the original embedding of item $i$. The embedding propagation can be computed recursively as:

$$
\begin{array}{l}
\mathbf{e}_{u}^{(k+1)}=\sigma\bigl( \mathbf{W}_{1}\mathbf{e}_{u}^{(k)} + \sum_{i \in \mathcal{N}_{u}} \frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}} (\mathbf{W}_{1}\mathbf{e}_{i}^{(k)} + \mathbf{W}_{2}(\mathbf{e}_{i}^{(k)}\cdot\mathbf{e}_{u}^{(k)}) ) \bigr)
\\
\mathbf{e}_{i}^{(k+1)}=\sigma\bigl( \mathbf{W}_{1}\mathbf{e}_{i}^{(k)} +\sum_{u \in \mathcal{N}_{i}} \frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}} (\mathbf{W}_{1}\mathbf{e}_{u}^{(k)} + \mathbf{W}_{2}(\mathbf{e}_{u}^{(k)}\cdot\mathbf{e}_{i}^{(k)}) ) \bigr)
\end{array}
$$

where $\mathbf{W}_{1}$ and $\mathbf{W}_{2}$ are trainable weight matrices, $\frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}}$ is a discount factor expressed as the graph Laplacian norm, $\mathcal{N}_{u}$ and $\mathcal{N}_{i}$ denote the first-hop neighbors of user $u$ and item $i$, and $\sigma$ is a non-linearity that in the paper is set as a LeakyReLU. 

To obtain the final representation, each propagated embedding is concatenated (i.e., $\mathbf{e}_{u}^{(*)}=\mathbf{e}_{u}^{(0)}||...||\mathbf{e}_{u}^{(l)}$), and then the final user's preference over an item is computed as a dot product: $\hat y_{u i} = \mathbf{e}_{u}^{(*)T}\mathbf{e}_{i}^{(*)}$.

### 1.2 LightGCN architecture

LightGCN is a simplified version of NGCF [4] to make it more concise and appropriate for recommendations. The model architecture is illustrated below.

<img src="https://raw.githubusercontent.com/recommenders-team/resources/main/images/lightGCN-model.jpg" width=600 style="display:block; margin-left:auto; margin-right:auto;">

In Light Graph Convolution, only the normalized sum of neighbor embeddings is performed towards next layer; other operations like self-connection, feature transformation via weight matrices, and nonlinear activation are all removed, which largely simplifies NGCF. In the layer combination step, instead of concatenating the embeddings, we sum over the embeddings at each layer to obtain the final representations.

### 1.3 Light Graph Convolution (LGC)

In LightGCN, we adopt the simple weighted sum aggregator and abandon the use of feature transformation and nonlinear activation. The graph convolution operation in LightGCN is defined as:

$$
\begin{array}{l}
\mathbf{e}_{u}^{(k+1)}=\sum_{i \in \mathcal{N}_{u}} \frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}} \mathbf{e}_{i}^{(k)} \\
\mathbf{e}_{i}^{(k+1)}=\sum_{u \in \mathcal{N}_{i}} \frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}} \mathbf{e}_{u}^{(k)}
\end{array}
$$

The symmetric normalization term $\frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}}$ follows the design of standard GCN, which can avoid the scale of embeddings increasing with graph convolution operations.


### 1.4 Layer Combination and Model Prediction

In LightGCN, the only trainable model parameters are the embeddings at the 0-th layer, i.e., $\mathbf{e}_{u}^{(0)}$ for all users and $\mathbf{e}_{i}^{(0)}$ for all items. When they are given, the embeddings at higher layers can be computed via LGC. After $K$ layers LGC, we further combine the embeddings obtained at each layer to form the final representation of a user (an item):

$$
\mathbf{e}_{u}=\sum_{k=0}^{K} \alpha_{k} \mathbf{e}_{u}^{(k)} ; \quad \mathbf{e}_{i}=\sum_{k=0}^{K} \alpha_{k} \mathbf{e}_{i}^{(k)}
$$

where $\alpha_{k} \geq 0$ denotes the importance of the $k$-th layer embedding in constituting the final embedding. In our experiments, we set $\alpha_{k}$ uniformly as $1 / (K+1)$.

The model prediction is defined as the inner product of user and item final representations:

$$
\hat{y}_{u i}=\mathbf{e}_{u}^{T} \mathbf{e}_{i}
$$

which is used as the ranking score for recommendation generation.


### 1.5 Matrix Form

Let the user-item interaction matrix be $\mathbf{R} \in \mathbb{R}^{M \times N}$ where $M$ and $N$ denote the number of users and items, respectively, and each entry $R_{ui}$ is 1 if $u$ has interacted with item $i$ otherwise 0. We then obtain the adjacency matrix of the user-item graph as

$$
\mathbf{A}=\left(\begin{array}{cc}
\mathbf{0} & \mathbf{R} \\
\mathbf{R}^{T} & \mathbf{0}
\end{array}\right)
$$

Let the 0-th layer embedding matrix be $\mathbf{E}^{(0)} \in \mathbb{R}^{(M+N) \times T}$, where $T$ is the embedding size. Then we can obtain the matrix equivalent form of LGC as:

$$
\mathbf{E}^{(k+1)}=\left(\mathbf{D}^{-\frac{1}{2}} \mathbf{A} \mathbf{D}^{-\frac{1}{2}}\right) \mathbf{E}^{(k)}
$$

where $\mathbf{D}$ is a $(M+N) \times(M+N)$ diagonal matrix, in which each entry $D_{ii}$ denotes the number of nonzero entries in the $i$-th row vector of the adjacency matrix $\mathbf{A}$ (also named as degree matrix). Lastly, we get the final embedding matrix used for model prediction as:

$$
\begin{aligned}
\mathbf{E} &=\alpha_{0} \mathbf{E}^{(0)}+\alpha_{1} \mathbf{E}^{(1)}+\alpha_{2} \mathbf{E}^{(2)}+\ldots+\alpha_{K} \mathbf{E}^{(K)} \\
&=\alpha_{0} \mathbf{E}^{(0)}+\alpha_{1} \tilde{\mathbf{A}} \mathbf{E}^{(0)}+\alpha_{2} \tilde{\mathbf{A}}^{2} \mathbf{E}^{(0)}+\ldots+\alpha_{K} \tilde{\mathbf{A}}^{K} \mathbf{E}^{(0)}
\end{aligned}
$$

where $\tilde{\mathbf{A}}=\mathbf{D}^{-\frac{1}{2}} \mathbf{A} \mathbf{D}^{-\frac{1}{2}}$ is the symmetrically normalized matrix.

### 1.6 Model Training

We employ the Bayesian Personalized Ranking (BPR) loss which is a pairwise loss that encourages the prediction of an observed entry to be higher than its unobserved counterparts:

$$
L_{B P R}=-\sum_{u=1}^{M} \sum_{i \in \mathcal{N}_{u}} \sum_{j \notin \mathcal{N}_{u}} \ln \sigma\left(\hat{y}_{u i}-\hat{y}_{u j}\right)+\lambda\left\|\mathbf{E}^{(0)}\right\|^{2}
$$

Where $\lambda$ controls the $L_2$ regularization strength. We employ the Adam optimizer and use it in a mini-batch manner.

## 2 PyTorch implementation of LightGCN with MovieLens dataset

We will use the MovieLens dataset, which is composed of integer ratings from 1 to 5.

We convert MovieLens into implicit feedback for model training and evaluation.

### 2.1 Load and split data

We split the full dataset into a `train` and `test` dataset to evaluate performance of the algorithm against a held-out set not seen during training. Because SAR generates recommendations based on user preferences, all users that are in the test set must also exist in the training set. For this case, we can use the provided `python_stratified_split` function which holds out a percentage (in this case 25%) of items from each user, but ensures all users are in both `train` and `test` datasets. Other options are available in the `dataset.python_splitters` module which provide more control over how the split occurs.

In [3]:
df = movielens.load_pandas_df(size=MOVIELENS_DATA_SIZE)

df.head()

Downloading http://files.grouplens.org/datasets/movielens/ml-100k.zip

  0%|          | 0.00/4.81k [00:00<?, ?KB/s]

  0%|          | 8.00/4.81k [00:00<01:47, 44.9KB/s]

  1%|          | 39.0/4.81k [00:00<00:41, 115KB/s]

  2%|▏         | 94.0/4.81k [00:00<00:24, 194KB/s]

  4%|▍         | 204/4.81k [00:00<00:13, 344KB/s]

  9%|▉         | 430/4.81k [00:00<00:06, 645KB/s]

 18%|█▊        | 883/4.81k [00:01<00:03, 1.23kKB/s]

 37%|███▋      | 1.78k/4.81k [00:01<00:01, 2.35kKB/s]

 65%|██████▌   | 3.14k/4.81k [00:01<00:00, 3.73kKB/s]

100%|██████████| 4.81k/4.81k [00:01<00:00, 2.97kKB/s]

   userID  itemID  rating  timestamp
0     196     242     3.0  881250949
1     186     302     3.0  891717742
2      22     377     1.0  878887116
3     244      51     2.0  880606923
4     166     346     1.0  886397596

In [4]:
train, test = python_stratified_split(df, ratio=0.75)

### 2.2 Process data

`ImplicitCF` is a class that intializes and loads data for the training process. During the initialization of this class, user IDs and item IDs are reindexed, ratings greater than zero are converted into implicit positive interaction, and adjacency matrix $R$ of user-item graph is created. Some important methods of `ImplicitCF` are:

`get_norm_adj_mat`, load normalized adjacency matrix of user-item graph if it already exists in `adj_dir`, otherwise call `create_norm_adj_mat` to create the matrix and save the matrix if `adj_dir` is not `None`. This method will be called during the initialization process of LightGCN model.

`create_norm_adj_mat`, create normalized adjacency matrix of user-item graph by calculating $D^{-\frac{1}{2}} A D^{-\frac{1}{2}}$, where $\mathbf{A}=\left(\begin{array}{cc}\mathbf{0} & \mathbf{R} \\ \mathbf{R}^{T} & \mathbf{0}\end{array}\right)$.

`train_loader`, generate a batch of training data — sample a batch of users and then sample one positive item and one negative item for each user. This method will be called before each epoch of the training process.

In [5]:
data = ImplicitCF(train=train, test=test, seed=SEED)

### 2.3 Create and train model

With data and parameters prepared, we can create the LightGCN model.

To train the model, we simply need to call the `fit()` method.

In [6]:
model = LightGCN(
    n_users=data.n_users,
    n_items=data.n_items,
    norm_adj=data.get_norm_adj_mat(),
    embed_size=64,
    n_layers=3,
    seed=SEED,
)

Already create adjacency matrix.

Already normalize adjacency matrix.

Using xavier initialization.

In [7]:
with Timer() as train_time:
    model.fit(
        data,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        learning_rate=5e-4,
        decay=0.0001,
        eval_epoch=5,
        top_k=TOP_K,
    )

print(f"Took {train_time.interval} seconds for training.")

Epoch 1 (train)1.3s: train loss = 0.68973 = (mf)0.68971 + (embed)0.00002

Epoch 2 (train)0.8s: train loss = 0.64013 = (mf)0.64009 + (embed)0.00004

Epoch 3 (train)0.8s: train loss = 0.52839 = (mf)0.52828 + (embed)0.00011

Epoch 4 (train)0.8s: train loss = 0.43216 = (mf)0.43196 + (embed)0.00019

Epoch 5 (train)0.8s + (eval)0.2s: train loss = 0.37391 = (mf)0.37364 + (embed)0.00028, recall = 0.11970, ndcg = 0.23170, precision = 0.20933, map = 0.11926

Epoch 6 (train)0.8s: train loss = 0.34613 = (mf)0.34579 + (embed)0.00034

Epoch 7 (train)0.8s: train loss = 0.33228 = (mf)0.33189 + (embed)0.00040

Epoch 8 (train)0.8s: train loss = 0.32281 = (mf)0.32237 + (embed)0.00044

Epoch 9 (train)0.8s: train loss = 0.31582 = (mf)0.31535 + (embed)0.00047

Epoch 10 (train)0.8s + (eval)0.4s: train loss = 0.31205 = (mf)0.31156 + (embed)0.00049, recall = 0.12400, ndcg = 0.23824, precision = 0.21336, map = 0.12351

Epoch 11 (train)0.8s: train loss = 0.30697 = (mf)0.30645 + (embed)0.00051

Epoch 12 (train)0.8s: train loss = 0.30453 = (mf)0.30400 + (embed)0.00053

Epoch 13 (train)0.8s: train loss = 0.30443 = (mf)0.30389 + (embed)0.00055

Epoch 14 (train)0.8s: train loss = 0.29905 = (mf)0.29849 + (embed)0.00056

Epoch 15 (train)0.8s + (eval)0.2s: train loss = 0.29833 = (mf)0.29775 + (embed)0.00057, recall = 0.13016, ndcg = 0.25965, precision = 0.22725, map = 0.13947

Epoch 16 (train)0.8s: train loss = 0.29304 = (mf)0.29246 + (embed)0.00058

Epoch 17 (train)0.8s: train loss = 0.29117 = (mf)0.29057 + (embed)0.00060

Epoch 18 (train)0.8s: train loss = 0.28519 = (mf)0.28459 + (embed)0.00061

Epoch 19 (train)0.8s: train loss = 0.28129 = (mf)0.28066 + (embed)0.00062

Epoch 20 (train)0.8s + (eval)0.4s: train loss = 0.28009 = (mf)0.27945 + (embed)0.00064, recall = 0.14234, ndcg = 0.28757, precision = 0.24761, map = 0.15997

Epoch 21 (train)0.8s: train loss = 0.27806 = (mf)0.27741 + (embed)0.00065

Epoch 22 (train)0.8s: train loss = 0.27233 = (mf)0.27167 + (embed)0.00066

Epoch 23 (train)0.8s: train loss = 0.26891 = (mf)0.26823 + (embed)0.00068

Epoch 24 (train)0.8s: train loss = 0.26709 = (mf)0.26640 + (embed)0.00069

Epoch 25 (train)0.8s + (eval)0.2s: train loss = 0.26381 = (mf)0.26311 + (embed)0.00071, recall = 0.14989, ndcg = 0.30892, precision = 0.26511, map = 0.17778

Epoch 26 (train)0.8s: train loss = 0.26240 = (mf)0.26167 + (embed)0.00072

Epoch 27 (train)0.8s: train loss = 0.25651 = (mf)0.25578 + (embed)0.00074

Epoch 28 (train)0.8s: train loss = 0.25744 = (mf)0.25668 + (embed)0.00075

Epoch 29 (train)0.8s: train loss = 0.25607 = (mf)0.25531 + (embed)0.00076

Epoch 30 (train)0.8s + (eval)0.4s: train loss = 0.25245 = (mf)0.25167 + (embed)0.00078, recall = 0.15254, ndcg = 0.32325, precision = 0.27985, map = 0.19234

Epoch 31 (train)0.8s: train loss = 0.25239 = (mf)0.25159 + (embed)0.00079

Epoch 32 (train)0.8s: train loss = 0.24901 = (mf)0.24820 + (embed)0.00081

Epoch 33 (train)0.8s: train loss = 0.24767 = (mf)0.24684 + (embed)0.00083

Epoch 34 (train)0.8s: train loss = 0.24352 = (mf)0.24267 + (embed)0.00085

Epoch 35 (train)0.8s + (eval)0.2s: train loss = 0.24454 = (mf)0.24368 + (embed)0.00086, recall = 0.15251, ndcg = 0.33215, precision = 0.28600, map = 0.20234

Epoch 36 (train)0.8s: train loss = 0.24014 = (mf)0.23927 + (embed)0.00088

Epoch 37 (train)0.8s: train loss = 0.24316 = (mf)0.24227 + (embed)0.00089

Epoch 38 (train)0.8s: train loss = 0.23975 = (mf)0.23884 + (embed)0.00091

Epoch 39 (train)0.8s: train loss = 0.23489 = (mf)0.23397 + (embed)0.00092

Epoch 40 (train)0.8s + (eval)0.4s: train loss = 0.23799 = (mf)0.23705 + (embed)0.00094, recall = 0.15460, ndcg = 0.33776, precision = 0.29056, map = 0.20783

Epoch 41 (train)0.8s: train loss = 0.23397 = (mf)0.23302 + (embed)0.00096

Epoch 42 (train)0.8s: train loss = 0.23577 = (mf)0.23480 + (embed)0.00097

Epoch 43 (train)0.8s: train loss = 0.23437 = (mf)0.23339 + (embed)0.00098

Epoch 44 (train)0.8s: train loss = 0.23225 = (mf)0.23126 + (embed)0.00099

Epoch 45 (train)0.8s + (eval)0.2s: train loss = 0.23428 = (mf)0.23328 + (embed)0.00101, recall = 0.15537, ndcg = 0.34202, precision = 0.29502, map = 0.21235

Epoch 46 (train)0.8s: train loss = 0.23229 = (mf)0.23127 + (embed)0.00102

Epoch 47 (train)0.8s: train loss = 0.23027 = (mf)0.22924 + (embed)0.00103

Epoch 48 (train)0.8s: train loss = 0.23157 = (mf)0.23052 + (embed)0.00105

Epoch 49 (train)0.8s: train loss = 0.22645 = (mf)0.22539 + (embed)0.00106

Epoch 50 (train)0.8s + (eval)0.4s: train loss = 0.22426 = (mf)0.22319 + (embed)0.00108, recall = 0.15754, ndcg = 0.34712, precision = 0.30053, map = 0.21730

Took 44.02048853226006 seconds for training.

### 2.4 Recommendation and Evaluation

Recommendation and evaluation have been performed on the specified test set during training. After training, we can also use the model to perform recommendation and evalution on other data. Here we still use `test` as test data, but `test` can be replaced by other data with similar data structure.

#### 2.4.1 Recommendation

We can call `recommend_k_items` to recommend k items for each user passed in this function. We set `remove_seen=True` to remove the items already seen by the user. The function returns a dataframe, containing each user and top k items recommended to them and the corresponding ranking scores.

In [8]:
topk_scores = model.recommend_k_items(test, top_k=TOP_K, remove_seen=True)

topk_scores.head()

   userID  itemID  prediction
0       1     181    6.552266
1       1     174    6.488816
2       1      98    6.194874
3       1     121    5.976821
4       1     204    5.873563

#### 2.4.2 Evaluation

With `topk_scores` predicted by the model, we can evaluate how LightGCN performs on this test set.

In [9]:
eval_map = map_at_k(test, topk_scores, k=TOP_K)
eval_ndcg = ndcg_at_k(test, topk_scores, k=TOP_K)
eval_precision = precision_at_k(test, topk_scores, k=TOP_K)
eval_recall = recall_at_k(test, topk_scores, k=TOP_K)

print(
    "MAP@K:\t%f" % eval_map,
    "NDCG:\t%f" % eval_ndcg,
    "Precision@K:\t%f" % eval_precision,
    "Recall@K:\t%f" % eval_recall,
    sep="\n",
)

MAP@K:	0.217299
NDCG:	0.347119
Precision@K:	0.300530
Recall@K:	0.157542

In [10]:
# Record results for tests - ignore this cell
store_metadata("map", eval_map)
store_metadata("ndcg", eval_ndcg)
store_metadata("precision", eval_precision)
store_metadata("recall", eval_recall)

### 2.5 Infer embeddings

With `infer_embedding` method of LightGCN model, we can export the embeddings of users and items in the training set to CSV files for future use.

In [11]:
model.infer_embedding(user_file, item_file)

## 3. Compare LightGCN with SAR and NCF

Here there are the performances of LightGCN compared to [SAR](../00_quick_start/sar_movielens.ipynb) and [NCF](../00_quick_start/ncf_movielens.ipynb) on MovieLens dataset of 100k and 1m. The method of data loading and splitting is the same as that described above and the GPU used was a GeForce GTX 1080Ti.

Settings common to the three models: `epochs=15, seed=42`.

Settings for LightGCN: `embed_size=64, n_layers=3, batch_size=1024, decay=0.0001, learning_rate=0.015 `.

Settings for SAR: `similarity_type="jaccard", time_decay_coefficient=30, time_now=None, timedecay_formula=True`.

Settings for NCF: `n_factors=4, layer_sizes=[16, 8, 4], batch_size=1024, learning_rate=0.001`.

| Data Size | Model    | Training time | Recommending time | MAP@10   | nDCG@10  | Precision@10 | Recall@10 |
| --------- | -------- | ------------- | ----------------- | -------- | -------- | ------------ | --------- |
| 100k      | LightGCN | 43.84      | 0.4           | 0.318966 | 0.463445 | 0.401803     | 0.218467  |
| 100k      | SAR      | 0.4895        | 0.1144            | 0.110591 | 0.382461 | 0.330753     | 0.176385  |
| 100k      | NCF      | 116.3174      | 7.7660            | 0.105725 | 0.387603 | 0.342100     | 0.174580  |
| 1m        | LightGCN | 1525.3827      | 3.0            | 0.281390 | 0.417519 | 0.382318     | 0.144888  |
| 1m        | SAR      | 4.5593        | 2.8357            | 0.060579 | 0.299245 | 0.270116     | 0.104350  |
| 1m        | NCF      | 1601.5846     | 85.4567           | 0.062821 | 0.348770 | 0.320613     | 0.108121  |

From the above results, we can see that LightGCN performs better than the other two models.

### References: 
1. Xiangnan He, Kuan Deng, Xiang Wang, Yan Li, Yongdong Zhang & Meng Wang, LightGCN: Simplifying and Powering Graph Convolution Network for Recommendation, 2020, https://arxiv.org/abs/2002.02126
2. LightGCN implementation [TensorFlow]: https://github.com/kuandeng/lightgcn
3. Thomas N. Kipf and Max Welling, Semi-Supervised Classification with Graph Convolutional Networks, ICLR, 2017, https://arxiv.org/abs/1609.02907
4. Xiang Wang, Xiangnan He, Meng Wang, Fuli Feng, and Tat-Seng Chua, Neural Graph Collaborative Filtering, SIGIR, 2019, https://arxiv.org/abs/1905.08108
5. Y. Koren, R. Bell and C. Volinsky, "Matrix Factorization Techniques for Recommender Systems", in Computer, vol. 42, no. 8, pp. 30-37, Aug. 2009, doi: 10.1109/MC.2009.263.  url: https://datajobs.com/data-science-repo/Recommender-Systems-%5BNetflix%5D.pdf